[package]
name = "client"
version = "0.1.0"
authors = ["Thomas Plisson <thomas.plisson@epitech.eu>"]
edition = "2018"

[dependencies]
types = { path = "../types" }
coffee = { version = "0.4", features = ["opengl"] }
serde = "1.0"
serde_derive = "1.0"
bincode = "1.3.1"
laminar = "0.5.0"
