[package]
name = "mazehem"
version = "0.1.0"
authors = [ "Thomas Plisson <thomas.plisson@epitech.eu>"]
edition = "2018"

[dependencies]
coffee = { version = "0.4", features = ["opengl"] }
rand = "0.8.4"